# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Apply AWS core config
on:
  push
env:
  AWS_REGION : "eu-central-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  apply-config:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/core_role
          role-session-name: github-session-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Test AWS CLI
        run: aws sts get-caller-identity
